// Code generated by mockery v2.20.0. DO NOT EDIT.

package counterVec

import mock "github.com/stretchr/testify/mock"

// CounterVecMock is an autogenerated mock type for the ICounterVec type
type CounterVecMock struct {
	mock.Mock
}

// CreateFailure provides a mock function with given fields: orgUid
func (_m *CounterVecMock) CreateFailure(orgUid string) {
	_m.Called(orgUid)
}

// CreateHit provides a mock function with given fields: orgUid
func (_m *CounterVecMock) CreateHit(orgUid string) {
	_m.Called(orgUid)
}

type mockConstructorTestingTNewCounterVecMock interface {
	mock.TestingT
	Cleanup(func())
}

// NewCounterVecMock creates a new instance of CounterVecMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCounterVecMock(t mockConstructorTestingTNewCounterVecMock) *CounterVecMock {
	mock := &CounterVecMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
